# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

In [2]:
df['col2'].unique()

array([444, 555, 666])

In [3]:
df['col2'].nunique()

3

In [4]:
df['col2'].value_counts()

444    2
666    1
555    1
Name: col2, dtype: int64

### Selecting Data

In [5]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [6]:
newdf

col1  col2 col3
3     4   444  xyz

### Applying Functions

In [7]:
#DataFrame: “index” (axis=0, default), “columns” (axis=1)
df.mean(0)

col1      2.50
col2    527.25
dtype: float64

In [8]:
df['col1'].mean()

2.5

In [9]:
df.mean(1)

0    222.5
1    278.5
2    334.5
3    224.0
dtype: float64

In [10]:
df_mean = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':[17,16,16,15]})
df_mean

col1  col2  col3
0     1   444    17
1     2   555    16
2     3   666    16
3     4   444    15

In [11]:
df_mean.mean(1)

0    154.000000
1    191.000000
2    228.333333
3    154.333333
dtype: float64

In [12]:
df_mean.loc[1].mean()

191.0

In [13]:
def times2(x):
    return x*2

In [14]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [15]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [16]:
df['col1'].sum()

10

In [17]:
#All such methods have a skipna option signaling whether to exclude missing data (True by default):
df.sum(0, skipna=False)

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [18]:
df.sum(0, skipna=True)

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [19]:
df.sum(1, skipna=False)

0    445
1    557
2    669
3    448
dtype: int64

In [20]:
#Series
#The idxmin() and idxmax() functions on Series and DataFrame compute the index labels with the 
#minimum and maximum corresponding values:
series_1 = pd.Series(np.random.randn(5))
series_1

0    0.946701
1    0.570103
2    0.879085
3   -0.087386
4    0.968701
dtype: float64

In [21]:
series_1.idxmin(), series_1.idxmax()

(3, 4)

In [22]:
df_1 = pd.DataFrame(np.random.randn(5,3), columns=['A','B','C'])
df_1

A         B         C
0  1.193064  0.519308 -1.250730
1  1.097420  1.022133 -0.525412
2  2.405602 -0.935680  0.017058
3  1.889161 -1.039267  0.747225
4 -0.750750 -0.764524 -1.647905

In [23]:
df_1.idxmin(axis=0)

A    4
B    3
C    4
dtype: int64

In [24]:
df_1.idxmax(axis=1)

0    A
1    A
2    A
3    A
4    A
dtype: object

In [25]:
df_3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))
df_3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [26]:
df_3['A'].idxmin()

'd'

In [27]:
#Note: idxminandidxmaxarecalledargminandargmaxinNumPy.

In [28]:
#value_counts()
data = np.random.randint(0, 7, size=50)
data

array([5, 0, 4, 1, 1, 5, 5, 4, 4, 1, 6, 1, 4, 2, 4, 2, 5, 0, 1, 3, 4, 3,
       3, 1, 2, 6, 4, 4, 3, 6, 5, 2, 2, 3, 0, 1, 3, 5, 2, 0, 6, 2, 1, 1,
       2, 0, 2, 5, 3, 3])

In [29]:
s = pd.Series(data)
s.value_counts()

1    9
2    9
3    8
4    8
5    7
0    5
6    4
dtype: int64

** Permanently Removing a Column**

In [30]:
del df['col1']

In [31]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Get column and index names: **

In [32]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [33]:
df.index

RangeIndex(start=0, stop=4, step=1)

** Sorting and Ordering a DataFrame:**

In [34]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [35]:
df.sort_values(by='col2') #inplace=False by default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

** Find Null Values or Check for Null Values**

In [36]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [37]:
# Drop rows with NaN Values
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Filling in NaN values with something else: **

In [38]:
import numpy as np

In [39]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [40]:
df.fillna('FILL')

col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

In [41]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [42]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [43]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

### Elementwise NumPy ufuncs (log, exp, sqrt, . . . ) and various other NumPy functions can be used with no issues on Series and DataFrame, assuming the data within are numeric:

In [44]:
df_1 = pd.DataFrame(np.random.randn(10, 4), columns=["A", "B", "C", "D"])
df_1

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1  1.090054  0.076370 -0.170899 -0.238919
2 -0.217728  0.162345  1.609782  1.133475
3 -0.005565 -0.827032 -0.242200  0.787729
4 -0.690215  1.053776 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128  0.807054  0.181827  0.219471
7 -0.605714 -0.636470  0.639624 -0.995050
8 -0.183659  0.819211 -0.198273 -0.738142
9  0.133825 -1.605063  1.524510 -0.736573

In [45]:
np.exp(df_1)

A         B         C         D
0  0.450675  0.361488  0.293816  0.358578
1  2.974434  1.079362  0.842907  0.787479
2  0.804344  1.176266  5.001719  3.106433
3  0.994450  0.437345  0.784900  2.198399
4  0.501468  2.868461  0.424874  0.410333
5  0.234862  0.661292  0.906436  0.312789
6  0.898411  2.241295  1.199407  1.245418
7  0.545685  0.529157  1.895768  0.369705
8  0.832220  2.268710  0.820146  0.478001
9  1.143192  0.200877  4.592894  0.478752

In [46]:
df_1 + df_1

A         B         C         D
0 -1.594016 -2.035052 -2.449603 -2.051221
1  2.180107  0.152740 -0.341798 -0.477838
2 -0.435456  0.324689  3.219563  2.266950
3 -0.011131 -1.654065 -0.484399  1.575458
4 -1.380430  2.107551 -1.711927 -1.781572
5 -2.897511 -0.827119 -0.196469 -2.324452
6 -0.214255  1.614107  0.363654  0.438942
7 -1.211427 -1.272939  1.279248 -1.990099
8 -0.367318  1.638423 -0.396545 -1.476283
9  0.267649 -3.210126  3.049021 -1.473146

In [47]:
1/df_1

A          B          C         D
0   -1.254693  -0.982776  -0.816459 -0.975029
1    0.917386  13.094156  -5.851412 -4.185516
2   -4.592891   6.159731   0.621202  0.882242
3 -179.682153  -1.209142  -4.128827  1.269472
4   -1.448824   0.948969  -1.168274 -1.122604
5   -0.690248  -2.418031 -10.179713 -0.860418
6   -9.334663   1.239075   5.499735  4.556406
7   -1.650945  -1.571167   1.563419 -1.004975
8   -5.444877   1.220686  -5.043560 -1.354753
9    7.472467  -0.623028   0.655948 -1.357639

In [48]:
df_1 - df_1.iloc[0]

A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  1.887062  1.093896  1.053902  0.786691
2  0.579280  1.179871  2.834583  2.159086
3  0.791443  0.190493  0.982602  1.813340
4  0.106793  2.071301  0.368838  0.134824
5 -0.651748  0.603966  1.126567 -0.136616
6  0.689880  1.824579  1.406628  1.245082
7  0.191294  0.381056  1.864425  0.030561
8  0.613349  1.836737  1.026529  0.287469
9  0.930833 -0.587537  2.749312  0.289038

In [49]:
#Boolean operators work as well:

df_bool1 = pd.DataFrame({'a': [1,0,0], 'b': [1,1,0]}, dtype=bool)
df_bool2 = pd.DataFrame({'a': [0,1,1], 'b': [1,0,1]}, dtype=bool)

df_bool1 & df_bool2

a      b
0  False   True
1  False  False
2  False  False

In [50]:
df_bool1 | df_bool2

a     b
0  True  True
1  True  True
2  True  True

In [51]:
np.asarray(df_1)

array([[-0.79700791, -1.01752579, -1.22480126, -1.02561038],
       [ 1.09005368,  0.07636995, -0.17089893, -0.23891915],
       [-0.21772779,  0.16234474,  1.60978161,  1.13347525],
       [-0.00556538, -0.8270324 , -0.24219953,  0.7877292 ],
       [-0.690215  ,  1.05377565, -0.85596362, -0.8907862 ],
       [-1.44875566, -0.41355957, -0.09823459, -1.1622262 ],
       [-0.10712759,  0.80705368,  0.18182695,  0.21947121],
       [-0.60571365, -0.63646968,  0.63962382, -0.99504952],
       [-0.18365889,  0.81921141, -0.19827265, -0.73814173],
       [ 0.13382461, -1.60506307,  1.5245104 , -0.73657287]])

## where()
In addition, where takes an optional other argument for replacement of values where the condition is False, in the returned copy.


In [53]:
df_1

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1  1.090054  0.076370 -0.170899 -0.238919
2 -0.217728  0.162345  1.609782  1.133475
3 -0.005565 -0.827032 -0.242200  0.787729
4 -0.690215  1.053776 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128  0.807054  0.181827  0.219471
7 -0.605714 -0.636470  0.639624 -0.995050
8 -0.183659  0.819211 -0.198273 -0.738142
9  0.133825 -1.605063  1.524510 -0.736573

In [54]:
df_1.where(df_1<0)

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1       NaN       NaN -0.170899 -0.238919
2 -0.217728       NaN       NaN       NaN
3 -0.005565 -0.827032 -0.242200       NaN
4 -0.690215       NaN -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128       NaN       NaN       NaN
7 -0.605714 -0.636470       NaN -0.995050
8 -0.183659       NaN -0.198273 -0.738142
9       NaN -1.605063       NaN -0.736573

In [55]:
df_1.where(df_1<0, -df_1)

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1 -1.090054 -0.076370 -0.170899 -0.238919
2 -0.217728 -0.162345 -1.609782 -1.133475
3 -0.005565 -0.827032 -0.242200 -0.787729
4 -0.690215 -1.053776 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128 -0.807054 -0.181827 -0.219471
7 -0.605714 -0.636470 -0.639624 -0.995050
8 -0.183659 -0.819211 -0.198273 -0.738142
9 -0.133825 -1.605063 -1.524510 -0.736573

In [56]:
df_orig = df_1.copy()
df_orig.where(df_1<0, -df_1, inplace=True)
df_orig

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1 -1.090054 -0.076370 -0.170899 -0.238919
2 -0.217728 -0.162345 -1.609782 -1.133475
3 -0.005565 -0.827032 -0.242200 -0.787729
4 -0.690215 -1.053776 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128 -0.807054 -0.181827 -0.219471
7 -0.605714 -0.636470 -0.639624 -0.995050
8 -0.183659 -0.819211 -0.198273 -0.738142
9 -0.133825 -1.605063 -1.524510 -0.736573

Note: The signature for DataFrame.where() differs from numpy.where(). Roughly df1.where(m, df2) is equivalent to np.where(m, df1, df2).

In [57]:
df_1.where(df_1 < 0, -df_1) == np.where(df_1 < 0, df_1, -df_1)

A     B     C     D
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True
4  True  True  True  True
5  True  True  True  True
6  True  True  True  True
7  True  True  True  True
8  True  True  True  True
9  True  True  True  True

In [58]:
np.where(df_1 < 0, df_1, -df_1)

array([[-0.79700791, -1.01752579, -1.22480126, -1.02561038],
       [-1.09005368, -0.07636995, -0.17089893, -0.23891915],
       [-0.21772779, -0.16234474, -1.60978161, -1.13347525],
       [-0.00556538, -0.8270324 , -0.24219953, -0.7877292 ],
       [-0.690215  , -1.05377565, -0.85596362, -0.8907862 ],
       [-1.44875566, -0.41355957, -0.09823459, -1.1622262 ],
       [-0.10712759, -0.80705368, -0.18182695, -0.21947121],
       [-0.60571365, -0.63646968, -0.63962382, -0.99504952],
       [-0.18365889, -0.81921141, -0.19827265, -0.73814173],
       [-0.13382461, -1.60506307, -1.5245104 , -0.73657287]])

In [64]:
df2 = df_1.copy()
df2.where(df_1<0, df_1['A'], axis='index')

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1  1.090054  1.090054 -0.170899 -0.238919
2 -0.217728 -0.217728 -0.217728 -0.217728
3 -0.005565 -0.827032 -0.242200 -0.005565
4 -0.690215 -0.690215 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128 -0.107128 -0.107128 -0.107128
7 -0.605714 -0.636470 -0.605714 -0.995050
8 -0.183659 -0.183659 -0.198273 -0.738142
9  0.133825 -1.605063  0.133825 -0.736573

In [66]:
df_1 

A         B         C         D
0 -0.797008 -1.017526 -1.224801 -1.025610
1  1.090054  0.076370 -0.170899 -0.238919
2 -0.217728  0.162345  1.609782  1.133475
3 -0.005565 -0.827032 -0.242200  0.787729
4 -0.690215  1.053776 -0.855964 -0.890786
5 -1.448756 -0.413560 -0.098235 -1.162226
6 -0.107128  0.807054  0.181827  0.219471
7 -0.605714 -0.636470  0.639624 -0.995050
8 -0.183659  0.819211 -0.198273 -0.738142
9  0.133825 -1.605063  1.524510 -0.736573

# Great Job!